---
services:
  nginxproxymanager:
    image: jc21/nginx-proxy-manager
    container_name: nginxproxymanager
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ~/nginx/data:/data
      - ~/nginx/letsencrypt:/etc/letsencrypt

  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - ~/adguard/conf:/opt/adguardhome/conf
      - ~/adguard/work:/opt/adguardhome/work
    ports:
      - 53:53
      - 53:53/udp

  syncthing:
    image: lscr.io/linuxserver/syncthing
    container_name: syncthing
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ~/syncthing/config:/config
      - ~/syncthing/data:/data
    ports:
      - 22000:22000
      - 21027:21027/udp

  duplicati:
    image: lscr.io/linuxserver/duplicati
    container_name: duplicati
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ~/duplicati/config:/config
      - ~/duplicati/backups:/backups
      - ~/duplicati/source:/source
      - ~/syncthing/data:/data/syncthing

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
