---
services:
  nginxproxymanager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginxproxymanager
    restart: unless-stopped
    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 81:81
      - 443:443
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - adguardhome_conf:/opt/adguardhome/conf
      - adguardhome_work:/opt/adguardhome/work
    ports:
      - 53:53
      - 53:53/udp
  syncthing:
    image: linuxserver/syncthing:latest
    container_name: syncthing
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - syncthing_config:/config
      - syncthing_data:/data
    ports:
      - 22000:22000
      - 21027:21027/udp
  duplicati:
    image: linuxserver/duplicati:latest
    container_name: duplicati
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - SETTINGS_ENCRYPTION_KEY=${DUPLICATI_SETTINGS_ENCRYPTION_KEY}
      - DUPLICATI__WEBSERVICE_PASSWORD=${DUPLICATI_WEBSERVICE_PASSWORD}
    volumes:
      - duplicati_config:/config
      - duplicati_backups:/backups
      - duplicati_source:/source
      - syncthing_data:/data/syncthing

volumes:
  adguardhome_conf:
  adguardhome_work:
  duplicati_backups:
  duplicati_config:
  duplicati_source:
  nginx_data:
  nginx_letsencrypt:
  syncthing_config:
  syncthing_data:
