---
services:
  tsdproxy:
    image: docker.io/almeidapaulopt/tsdproxy:1
    container_name: tsdproxy
    restart: unless-stopped
    volumes:
      - tsdproxy_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tsdproxy.yaml:/config/tsdproxy.yaml
    ports:
      - 8080:8080
    labels:
      - diun.enable=true
      - tsdproxy.enable=true
      - tsdproxy.name=dashboard
      - tsdproxy.dash.label=Dashboard
      - tsdproxy.dash.icon=si/tailscale
  diun:
    image: docker.io/crazymax/diun:latest
    command: serve
    container_name: diun
    restart: always
    environment:
      - TZ=${TZ}
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 * * * */1
      - DIUN_WATCH_JITTER=30s
      - DIUN_PROVIDERS_DOCKER=true
    volumes:
      - diun_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - diun.enable=true
  adguardhome:
    image: docker.io/adguard/adguardhome:latest
    container_name: adguardhome
    restart: always
    volumes:
      - adguardhome_conf:/opt/adguardhome/conf
      - adguardhome_work:/opt/adguardhome/work
    ports:
      - 53:53
      - 53:53/udp
      - 80:80
      - 3000:3000
    labels:
      - diun.enable=true
      - tsdproxy.enable=true
      - tsdproxy.name=adguardhome
      - tsdproxy.container_port=80
      - tsdproxy.dash.label=Adguard Home
      - tsdproxy.dash.icon=si/adguard
  syncthing:
    image: docker.io/linuxserver/syncthing:latest
    container_name: syncthing
    restart: always
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - syncthing_config:/config
      - syncthing_data:/data
    ports:
      - 21027:21027/udp
      - 22000:22000
      - 22000:22000/udp
      - 8384:8384
    labels:
      - diun.enable=true
      - tsdproxy.enable=true
      - tsdproxy.name=syncthing
      - tsdproxy.container_port=8384
      - tsdproxy.dash.label=Syncthing
      - tsdproxy.dash.icon=si/syncthing
  duplicati:
    image: docker.io/linuxserver/duplicati:latest
    container_name: duplicati
    restart: always
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - DUPLICATI__WEBSERVICE_PASSWORD=${DUPLICATI_WEBSERVICE_PASSWORD}
      - SETTINGS_ENCRYPTION_KEY=${DUPLICATI_SETTINGS_ENCRYPTION_KEY}
    volumes:
      - duplicati_config:/config
      - duplicati_backups:/backups
      - duplicati_source:/source
      - syncthing_data:/syncthing
    ports:
      - 8200:8200
    labels:
      - diun.enable=true
      - tsdproxy.enable=true
      - tsdproxy.name=duplicati
      - tsdproxy.container_port=8384
      - tsdproxy.dash.label=Duplicati
      - tsdproxy.dash.icon=si/duplicati
  atuin:
    image: ghcr.io/atuinsh/atuin:latest
    container_name: atuin
    restart: always
    command: server start
    volumes:
      - atuin_conf:/config
    ports:
      - 8888:8888
    environment:
      ATUIN_HOST: "0.0.0.0"
      ATUIN_OPEN_REGISTRATION: true
      ATUIN_DB_URI: postgres://$ATUIN_DB_USERNAME:$ATUIN_DB_PASSWORD@postgresql/$ATUIN_DB_NAME
      RUST_LOG: info,atuin_server=debug
    labels:
      - diun.enable=true
      - tsdproxy.enable=true
      - tsdproxy.container_port=8888
      - tsdproxy.dash.visible=false
  postgresql:
    image: docker.io/postgres:14
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${ATUIN_DB_USERNAME}
      POSTGRES_PASSWORD: ${ATUIN_DB_PASSWORD}
      POSTGRES_DB: ${ATUIN_DB_NAME}
  sftpgo:
    image: docker.io/drakkan/sftpgo:latest
    container_name: sftpgo
    restart: always
    volumes:
      - sftpgo_data:/var/lib/sftpgo
      - syncthing_data:/syncthing
    ports:
      - 8081:8080
      - 2022:2022
    labels:
      - diun.enable=true
      - tsdproxy.enable=true
      - tsdproxy.name=sftpgo
      - tsdproxy.container_port=8081
      - tsdproxy.dash.label=SFTPGo
      - tsdproxy.dash.icon=si/files

volumes:
  adguardhome_conf:
  adguardhome_work:
  atuin_conf:
  diun_data:
  duplicati_backups:
  duplicati_config:
  duplicati_source:
  postgres_data:
  syncthing_config:
  syncthing_data:
  tsdproxy_data:
  sftpgo_data:
