---
- name: Configure orangepizero2
  hosts: all
  become: true
  vars:
    ansible_user: phrmendes
    ansible_become_user: root
  vars_files:
    - secrets.yaml

  roles:
    - role: geerlingguy.docker
      tags: docker
      vars:
        docker_install_compose_plugin: true
        docker_packages_state: present
        docker_users:
          - "{{ ansible_user }}"

    - role: artis3n.tailscale.machine
      tags: tailscale
      vars:
        tailscale_tags: ["main"]
        tailscale_oauth_ephemeral: false
        tailscale_oauth_preauthorized: true
        tailscale_authkey: "{{ ts_orangepizero2_authkey }}"
        tailscale_args: "--reset --advertise-exit-node"

  handlers:
    - name: Restart Docker Compose
      community.docker.docker_compose_v2:
        project_src: /home/{{ ansible_user }}/compose
        state: present

  tasks:
    - name: Add user tool configurations
      tags: tools
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0644"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      loop:
        - src: ./init.vim
          dest: /home/{{ ansible_user }}/.vimrc
        - src: ./tmux.conf
          dest: /home/{{ ansible_user }}/.tmux.conf

    - name: Firewall settings
      tags: firewall
      block:
        - name: Install UFW firewall
          ansible.builtin.apt:
            name: ufw
            state: present

        - name: Set default UFW policies
          community.general.ufw:
            default: "{{ item.policy }}"
            direction: "{{ item.direction }}"
          loop:
            - policy: deny
              direction: incoming
            - policy: allow
              direction: outgoing

        - name: Allow OpenSSH for remote access
          community.general.ufw:
            rule: allow
            name: OpenSSH

        - name: Allow necessary TCP ports
          community.general.ufw:
            rule: allow
            port: "{{ item }}"
            proto: tcp
          loop: [53, 80, 8080, 8081, 22000, 2022]

        - name: Allow necessary UDP ports
          community.general.ufw:
            rule: allow
            port: "{{ item }}"
            proto: udp
          loop: [53, 21027]

    - name: Install Python dependencies for Docker management
      ansible.builtin.apt:
        name:
          - python3-requests
          - python3-yaml
        state: present

    - name: Docker setup
      tags: docker_compose
      block:
        - name: Ensure systemd service directory exists
          ansible.builtin.file:
            path: /etc/systemd/system
            state: directory
            mode: "0755"

        - name: Deploy Docker Compose systemd service
          ansible.builtin.copy:
            src: ./docker-compose.service
            dest: /etc/systemd/system/docker-compose.service
            mode: "0644"
            owner: root
            group: root

        - name: Deploy Docker Compose configuration
          ansible.builtin.copy:
            src: ./compose
            dest: /home/{{ ansible_user }}
            mode: "0644"
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"
          notify: Restart Docker Compose

        - name: Create .env file
          ansible.builtin.template:
            src: ./templates/env.j2
            dest: /home/{{ ansible_user }}/compose/.env
            mode: "0644"
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"

        - name: Deploy TSDProxy configuration
          ansible.builtin.template:
            src: ./templates/tsdproxy.yaml.j2
            dest: /home/{{ ansible_user }}/compose/tsdproxy-config.yaml
            mode: "0644"
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"

        - name: Enable and start docker-compose service
          ansible.builtin.systemd:
            name: docker-compose
            enabled: true
            state: started
