---
- name: Configure orangepizero2
  hosts: all
  become: true
  vars:
    ansible_user: phrmendes
    ansible_become_user: root
  vars_files:
    - secrets.yaml

  roles:
    - role: geerlingguy.docker
      vars:
        docker_install_compose_plugin: true
        docker_packages_state: present
        docker_users:
          - "{{ ansible_user }}"

    - role: artis3n.tailscale
      vars:
        tailscale_authkey: "{{ ts_authkey }}"

  tasks:
    - name: Add user tool configurations
      tags: tools
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0644"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      loop:
        - src: ./init.vim
          dest: /home/{{ ansible_user }}/.vimrc
        - src: ./tmux.conf
          dest: /home/{{ ansible_user }}/.tmux.conf

    - name: Firewall settings
      tags: firewall
      block:
        - name: Install UFW firewall
          ansible.builtin.apt:
            name: ufw
            state: present

        - name: Set default UFW policies
          community.general.ufw:
            default: "{{ item.policy }}"
            direction: "{{ item.direction }}"
          loop:
            - { policy: deny, direction: incoming }
            - { policy: allow, direction: outgoing }

        - name: Allow OpenSSH for remote access
          community.general.ufw:
            rule: allow
            name: OpenSSH

        - name: Allow necessary TCP ports
          community.general.ufw:
            rule: allow
            port: "{{ item }}"
            proto: tcp
          loop: [53, 80, 8080, 22000]

        - name: Allow necessary UDP ports
          community.general.ufw:
            rule: allow
            port: "{{ item }}"
            proto: udp
          loop: [53, 21027]

    - name: Set up required directories and files
      tags: file_setup
      become: true
      become_user: "{{ ansible_user }}"
      block:
        - name: Create necessary directories with permissions
          ansible.builtin.file:
            path: "{{ item.path }}"
            state: directory
            mode: "{{ item.mode | default('0666') }}"
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"
          loop:
            - path: /home/{{ ansible_user }}/adguard/conf
            - path: /home/{{ ansible_user }}/adguard/work
            - path: /home/{{ ansible_user }}/compose
            - path: /home/{{ ansible_user }}/duplicati/backups
            - path: /home/{{ ansible_user }}/duplicati/config
            - path: /home/{{ ansible_user }}/duplicati/source
            - path: /home/{{ ansible_user }}/nginx/data
            - path: /home/{{ ansible_user }}/nginx/letsencrypt
              mode: "0744"
            - path: /home/{{ ansible_user }}/syncthing/config
            - path: /home/{{ ansible_user }}/syncthing/data

        - name: Copy AdGuardHome configuration
          ansible.builtin.template:
            src: ./AdGuardHome.yaml.j2
            dest: /home/{{ ansible_user }}/adguard/conf/AdGuardHome.yaml
            mode: "0666"
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"

        - name: Deploy Docker Compose configuration
          ansible.builtin.copy:
            src: ./docker-compose.yaml
            dest: /home/{{ ansible_user }}/compose/docker-compose.yaml
            mode: "0666"
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"
          notify: Restart Docker containers

    - name: Docker setup
      tags: docker
      block:
        - name: Install Python dependencies for Docker management
          ansible.builtin.apt:
            name:
              - python3-requests
              - python3-yaml
            state: present

        - name: Remove dnsmasq to prevent conflicts
          ansible.builtin.apt:
            name: dnsmasq
            state: absent

        - name: Run Docker Compose to launch services
          community.docker.docker_compose_v2:
            project_src: /home/{{ ansible_user }}/compose
            state: present
          environment:
            CLOUDFLARE_TOKEN: "{{ cloudflare_token }}"
            SB_USER: "{{ ansible_user }}:{{ silverbullet_password }}"

  handlers:
    - name: Restart Docker containers
      ansible.builtin.service:
        name: docker
        state: restarted
