services:
  adguardhome:
    image: docker.io/adguard/adguardhome:latest
    container_name: adguardhome
    restart: always
    volumes:
      - adguardhome_conf:/opt/adguardhome/conf
      - adguardhome_work:/opt/adguardhome/work
    ports:
      - 53:53
      - 53:53/udp
      - 80:80
      - 3000:3000
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=adguardhome
      - tsdproxy.container_port=80
      - tsdproxy.dash.label=Adguard Home
      - tsdproxy.dash.icon=sh/adguard-home

volumes:
  adguardhome_conf:
  adguardhome_work:
