services:
  atuin:
    image: ghcr.io/atuinsh/atuin:latest
    container_name: atuin
    restart: always
    command: server start
    volumes:
      - atuin_conf:/config
    ports:
      - 8888:8888
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ATUIN_HOST=0.0.0.0
      - ATUIN_OPEN_REGISTRATION=true
      - ATUIN_DB_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/atuin
      - RUST_LOG=info,atuin_server=debug
    labels:
      - diun.enable=true
      - tsdproxy.enable=true
      - tsdproxy.container_port=8888
      - tsdproxy.dash.visible=false

volumes:
  atuin_conf:
