services:
  beszel-agent:
    image: docker.io/henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: always
    network_mode: host
    volumes:
      - beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - LISTEN=/beszel_socket/beszel.sock
      - KEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILXOuqiQ3BVQvmydoVRq2lSRhKb1MzvJv8+3JEdn+eeP
  beszel:
    image: docker.io/henrygd/beszel:latest
    container_name: beszel
    restart: always
    ports:
      - 8090:8090
    volumes:
      - beszel_data:/beszel_data
      - beszel_socket:/beszel_socket
    labels:
      - diun.enable=true
      - tsdproxy.enable=true
      - tsdproxy.name=beszel
      - tsdproxy.container_port=8090
      - tsdproxy.dash.label=Beszel
      - tsdproxy.dash.icon=sh/beszel
    depends_on:
      - beszel-agent

volumes:
  beszel_data:
  beszel_socket:
