services:
  diun:
    image: docker.io/crazymax/diun:latest
    command: serve
    container_name: diun
    restart: always
    environment:
      - TZ=${TZ}
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 * * * */1
      - DIUN_WATCH_JITTER=30s
      - DIUN_PROVIDERS_DOCKER=true
    volumes:
      - diun_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - diun.enable=true

volumes:
  diun_data:
