services:
  syncthing:
    image: docker.io/linuxserver/syncthing:latest
    container_name: syncthing
    restart: always
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - syncthing_config:/config
      - syncthing_data:/data
    ports:
      - 21027:21027/udp
      - 22000:22000
      - 22000:22000/udp
      - 8384:8384
    labels:
      - diun.enable=true
      - tsdproxy.enable=true
      - tsdproxy.name=syncthing
      - tsdproxy.container_port=8384
      - tsdproxy.dash.label=Syncthing
      - tsdproxy.dash.icon=sh/syncthing

volumes:
  syncthing_config:
  syncthing_data:
